version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mvrr_db
      # POSTGRES_STATEMENT_TIMEOUT: 10000
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backup:/backup
      - ./backups:/backups
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin2
    depends_on:
      - postgres
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: unnimaya@gmail.com
      PGADMIN_DEFAULT_PASSWORD: unnimaya@123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Reon@123
    ports:
      - '30000:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  postgres-data:
  pgadmin-data:
  mongo-data:
